trigger:
- master

pr:
 autoCancel: true
 branches:
   include:
     - master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'



steps:
- task: DotNetCoreCLI@2
  displayName: 'Build solution'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: test
    projects: 'tests/**/*UnitTests*.csproj'
    arguments: '--no-build --no-restore --collect "Code coverage"'

