//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Identity.Extensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Identity.Extensions.Msal.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additionalContext must be of type JsonRpc.
        /// </summary>
        internal static string AdditionalContextMustBeJsonRpc {
            get {
                return ResourceManager.GetString("AdditionalContextMustBeJsonRpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub account.
        /// </summary>
        internal static string GitHubAccountProviderName {
            get {
                return ResourceManager.GetString("GitHubAccountProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get details about the home tenant.
        /// </summary>
        internal static string HomeTenantInformationNotFound {
            get {
                return ResourceManager.GetString("HomeTenantInformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecKeychainItemDelete failed with error code: {0}.
        /// </summary>
        internal static string MacKeyChainDeleteFailed {
            get {
                return ResourceManager.GetString("MacKeyChainDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecKeychainFindGenericPassword failed with error code: {0}.
        /// </summary>
        internal static string MacKeyChainFindFailed {
            get {
                return ResourceManager.GetString("MacKeyChainFindFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecKeychainAddGenericPassword failed with error code: {0}.
        /// </summary>
        internal static string MacKeyChainInsertFailed {
            get {
                return ResourceManager.GetString("MacKeyChainInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecKeychainItemModifyAttributesAndData failed with error code: {0}.
        /// </summary>
        internal static string MacKeyChainUpdateFailed {
            get {
                return ResourceManager.GetString("MacKeyChainUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No home tenant could be found.
        /// </summary>
        internal static string NoHomeTenantFound {
            get {
                return ResourceManager.GetString("NoHomeTenantFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session token entry found.
        /// </summary>
        internal static string NoSessionTokenFound {
            get {
                return ResourceManager.GetString("NoSessionTokenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry count exceeded.
        /// </summary>
        internal static string RetryCountExceeded {
            get {
                return ResourceManager.GetString("RetryCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get the list of tenants.
        /// </summary>
        internal static string TenantInformationNotFound {
            get {
                return ResourceManager.GetString("TenantInformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft account.
        /// </summary>
        internal static string VsAccountProviderName {
            get {
                return ResourceManager.GetString("VsAccountProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account provider is not supported.
        /// </summary>
        internal static string VsAccountProviderUnsupportedAccount {
            get {
                return ResourceManager.GetString("VsAccountProviderUnsupportedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is not supported by this provider. The configuration does not match..
        /// </summary>
        internal static string VsAccountProviderUnsupportedConfiguration {
            get {
                return ResourceManager.GetString("VsAccountProviderUnsupportedConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work or school account.
        /// </summary>
        internal static string VsAccountProviderWorkOrSchool {
            get {
                return ResourceManager.GetString("VsAccountProviderWorkOrSchool", resourceCulture);
            }
        }
    }
}
